name: vmlinux.h

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gen-headers:
    name: Generate vmlinux.h
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Check out Linux source
        uses: actions/checkout@v6
        with:
          repository: 'torvalds/linux'
          ref: 'v6.18'
          fetch-depth: 1
          path: linux/

      - name: Check out pahole source
        uses: actions/checkout@v6
        with:
          repository: 'acmel/dwarves'
          ref: 'next'
          fetch-depth: 1
          path: pahole/

      - name: Install pahole
        shell: bash
        run: |
          sudo apt -y install cmake git libdw-dev libelf-dev
          cd pahole
          mkdir -p build
          cmake -B=build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          make -C build -j$(nproc)
          sudo make -C build install

      - name: Install dependencies
        shell: bash
        run: |
          ./scripts/install-dependencies.sh
          ./scripts/install-bpftool.sh

      - name: x86_64/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh x86_64

      - name: aarch64/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh aarch64

      - name: arm/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh arm

      - name: loongarch64/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh loongarch64

      - name: ppc64le/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh ppc64le

      - name: riscv64/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh riscv64

      - name: s390x/vmlinux.h
        shell: bash
        run: ./scripts/gen-vmlinux-header.sh s390x

      - name: Upload headers
        uses: actions/upload-artifact@v4
        with:
          name: vmlinux.h
          if-no-files-found: error
          path: ./vmlinux.h
